name: scikit-hep-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.8
  - sphinx=2.4.4
  - pip
  - pandas
  - matplotlib
  - root
  - jupyterlab
  - pip:
    - jupyter-book>=0.9.0
    - scikit-hep>=1.3.0
    - git+https://github.com/scikit-hep/aghast#subdirectory=python
