name: scikit-hep-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas
  - matplotlib
  - root
  - jupyterlab
  - jupyter-book>=0.10.0
  - scikit-hep>=3.0.0
  - pip:
    - git+https://github.com/scikit-hep/aghast#subdirectory=python
